# Site
repository: Dylan-Lawless/modern-resume-theme
favicon: images/favicon.ico

# Personal info
name: Dylan Lawless
title: Postdoctoral researcher
email: dylan.lawless@epfl.ch
website: https://dylanlawlessblog.wordpress.com

# Social links
twitter_username: meddlaw
# github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: lawless.ch
linkedin_username: dylan lawless
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-8496-3725

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
  
# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Tester Hi, my name is Dylan and I'm a post-doc scientist.
  Highly motivated & committed. Speciality: Human genomics & immunology. Style: Working with a wide range of specialists from international teams. Aim: To organise large, collaborative research projects in human health with a lasting impact based on open, reproducible science. 
  Key skills: Collaborative, Big data analysis, Project management, Extract & visualise key data, Making complex systems simple 
  
  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: Dylan-Lawless/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

future: true
